
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8759/eureka/,http://localhost:8760/eureka/,http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  rabbitmq:
    username: rabbit
    password: 123456
zuul:
  routes:
    zuul-server:
      path: /test/**
      url: http://127.0.0.1:9090/
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: service-ribbon
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign