spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        accept-empty: false
  profiles:
    active: git
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost-1:8759/eureka/,http://localhost-2:8760/eureka/,http://localhost-3:8761/eureka/
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: